### ISSUE TITLE
Unable to build with Arduino-Source-0.40 or higher on Mac 

### ISSUE THREAD

**Issue by Grantys** [PokemonAutomation/Arduino-Source#371]
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
System: OSX 13.4.1c
Arduino Source version: Arduino-Source-0.40 or master (earlier versions work)
**Issue Statement:** When executing the `cmake --build . -j 10` I'm receiving the following error and process ends:

"CroppedImageDictionaryMatcher.cpp:73:16: error: variable 'c' set but not used [-Werror,-Wunused-but-set-variable]
        size_t c = 0;
               ^
[ 15%] Building CXX object CMakeFiles/SerialPrograms.dir/Source/CommonFramework/ImageTools/FloatPixel.cpp.o
[ 15%] Building CXX object CMakeFiles/SerialPrograms.dir/Source/CommonFramework/ImageTools/ImageBoxes.cpp.o
1 error generated.
gmake[2]: *** [CMakeFiles/SerialPrograms.dir/build.make:1845: CMakeFiles/SerialPrograms.dir/Source/CommonFramework/ImageMatch/CroppedImageDictionaryMatcher.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/SerialPrograms.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2"

**Workaround I've used:**
adding `#pragma GCC diagnostic ignored "-Wunused-but-set-variable"` to Common/Compiler.h
This made sure the process ends, but I'm not yet sure if it causing any troubles for the usage of the tool.

**Comment by denvoros** [comment]
Instead of adding a whole pragma statement to Common/Compiler.h which could remove any other developer insights, we should just comment out or remove the unused variable or remove that part entirely.

Adding pragmas that disable entire diagnostics is not a recommended course of action because it could disable warnings and notes regarding optimizations that we might want to look for elsewhere. Putting that pragma in `Compiler.h` disables the warnings across the entire project. Yes, Mac's clang is annoying that it's enabled by default, but it's a good indicator for us when we can fix the program.

If you look at the `CroppedImageDictionaryMatcher.cpp` file, you'll notice that the variable `c` *was* used by something commented out. The compiler is basically tell you that it's safe to just comment those out. If you want to try commenting it out. So, try editing `CroppedImageDictionaryMatcher.cpp` on line 73 and comment out the line.

After you comment that out, you can submit a pull request if everything works.

**Comment by Mysticial** [comment]
I don't think the OP intended this to actually go in since they mentioned it as a workaround.

In any case, I've already deleted that unused line.
